### PR TITLE
Update Logo's to point to theming instead of a static indigo theme

### PR DESCRIPTION
**Pull request by misilot**
Also updated the link to the docs.

### CODE REVIEW

**Comment by hinakhadim** [comment]
Hi @misilot,

Can you please make the Link commit message and tests pass? Currently these two actions are not able to pass. For commit message, please follow the [guidelines](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html).

**Comment by hinakhadim** [comment]
Hey @misilot , any update?

**Comment by misilot** [comment]
Hi @hinakhadim I fixed the commit message. I don't think the tests were related to my PR, but it looks like they need to be approved to run.

**Comment by misilot** [comment]
Hello @hinakhadim is this test failure related to my PR?  I didn't touch any textual strings in my change.

**Comment by hinakhadim** [comment]
> Hello @hinakhadim is this test failure related to my PR? I didn't touch any textual strings in my change.

Yes. Actually the test cases are failing because the current code is tested again already build snapshot which has previous url. Run `npm run snapshot` and create commit and push. It will make the tests pass.

**Comment by misilot** [comment]
Thanks!

I had to run `npm install` as well.

Hopefully this fixes it?

**Comment by hinakhadim** [comment]
Great! all fixed now.

**Pull request merged**
